# Use a Java image
FROM eclipse-temurin:17-jdk

# Set working directory inside container
WORKDIR /app

# Copy only Maven files first (for caching dependencies)
COPY pom.xml .
COPY mvnw .
COPY .mvn .mvn

# Download dependencies
RUN ./mvnw dependency:go-offline -B

# Copy the rest of the backend source code
COPY . .

# Expose Spring Boot default port
EXPOSE 8080

# Run Spring Boot in dev mode
CMD ["./mvnw", "spring-boot:run"]
