FROM node:18

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY . .

# Expose Angular default dev port
EXPOSE 4200

# Start Angular in dev mode
CMD ["npm", "start"]
